### ISSUE TITLE
Shiny app logs not making it into Kibana

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#10]
## What happened?

when `logstash-apps-alpha` is selected in Kibana, nothing shows up.

## Steps to reproduce the problem

Go to the Kibana dashboard and try and find logs created by apps

## Expected behaviour
We expect to see R Shiny logs.

To note:  The process of findings these logs when running Shiny apps in Docker on a macbook is documented [here](https://moj-analytical-services.github.io/platform_user_guidance/deploying-a-shiny-app.html#advanced-deployment).  Ideally these are the logs that we want to see in Kibana.

**Comment by kerin** [comment]
Fixed with recent updates to Fluentd config.
