### ISSUE TITLE
403 error when changing webapp bucket access permissions

### ISSUE THREAD

**Issue by calumabarnett** [ministryofjustice/analytics-platform#108]
## What happened?
@MeganStodel reported receiving a '403 Forbidden' error when trying to change the bucket access permissions of the novel-drug-words-app from read only to read/write.

## Steps to reproduce the problem
1. Open the 'Webapps' page
2. Select the 'novel-drug-words-app'
3. In the 'App data sources' section select 'Set read/write' for the 'alpha-app-novel-drug-words' bucket
4. Receive a '403 Forbidden' error.

![MSerror](https://user-images.githubusercontent.com/46442591/63015971-468e3580-be8a-11e9-8516-ecbebdfd0455.png)

## Expected behaviour
The user expected the bucket access permissions for the app to be changed to read/write.

**Comment by andyhd** [comment]
Fixed
