### ISSUE TITLE
Fix files being corrupted on RStudio upload (e.g. xlsx)

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#11]
## What happened?

When using the upload button in R Studio, files get corrupted if the filetype is non-text.  So, e.g. World (xlsx) files get corrupted, and so do .xlsx, but .csv files seem to be fine.

Need to verify that the file on the platform is identical to the file on the user's local machine (e.g. the checksum is the same, or some other similar method)

**Comment by andyhd** [comment]
This is the root cause of issue #6

**Comment by andyhd** [comment]
I've fixed this bug in the latest version of the RStudio proxy. You will need to redeploy RStudio for affected (all) users.
