### ISSUE TITLE
Unidler page is missing GOV.UK styling

### ISSUE THREAD

**Issue by calumabarnett** [ministryofjustice/analytics-platform#112]
## What happened?

When unidling analytical tools, the unidler page is missing GOV.UK styling.

![unidling](https://user-images.githubusercontent.com/46442591/65059368-ce75cc80-d96d-11e9-8e43-b831d9fd49d6.PNG)

## Steps to reproduce the problem

1. Open an idled analytical tool

## Expected behaviour

The unidler page has GOV.UK styling.

**Comment by andyhd** [comment]
I think it was loading static assets from the old control panel frontend - similar to the crown logo on the auth0 login page.
