### ISSUE TITLE
NOMIS login for AP not working for some Quantum users

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#113]
The Auth0 login page (for SDT) doesn't show for some users - this includes various prison staff (Quantum). It doesn't affect me when using it on Quantum at HQ.

This is what they see:
![image (8)](https://user-images.githubusercontent.com/307612/65868119-3b726480-e367-11e9-80cd-6964b47fb440.png)

This is what they should see:
<img width="1200" alt="Screen Shot 2019-09-30 at 11 26 33" src="https://user-images.githubusercontent.com/307612/65870914-d15cbe00-e36c-11e9-9bc1-a6acfa584699.png">

They are using Firefox 52ESR. We've tried this on our Macbooks and it loads it fine.

The page load stopping at this point suggests a problem with: https://cdn.auth0.com/js/lock/11.3/lock.min.js being loaded & run. The user is able to browse to that URL ok and see the js, so it is not blocked. However the SHA error suggests the javascript files [lock.min.js](https://cdn.auth0.com/js/lock/11.3/lock.min.js) and [sentry JS](https://browser.sentry-cdn.com/5.6.3/bundle.min.js) are corrupted en-route:
```None of the "sha384" hashes in the integrity attribute match the content of the subresource``` to do with Sentry and Auth0Lock

This issues is also noted in our SDT trello: https://trello.com/c/a3aW3Vey/39-auth0-page-doesnt-load-properly

**Comment by r4vi** [comment]
it feels like there is a content inspection proxy server in the way, and it somehow changes the sentry js causing the sha384 error. 
It is probably doing this for the traffic to the rshiny app causing problems with inputs being cleared too

**Comment by davidread** [comment]
JP reports what seems like a related issue with Shiny app prison-network-app:
> The data that has been inputted into a text box regularly gets wiped. Whenever they zoom out, click on another tab, or try to adjust their search, the data often gets wiped.
> This is using the visNetwork and igraph packages to visualise networks as well as some radio buttons etc. to filter the network being plotted. No errors show up in Kibana and I've turned off as many websockets as I can I think.

**Comment by r4vi** [comment]
by
> I've turned off as many websockets as I can I think.
Joe means the ALLOWED_PROTOCOLS for `sock.js` as described here: https://github.com/ministryofjustice/analytics-platform-shiny-server#configuration

**Comment by davidread** [comment]
The users in question have reported they have fixed the issue. This was achieved by installing HMPSNOMSROOT.crt into Firefox as a trusted root Certificate Authority (CA). So I guess they have a mitm which was rejecting these requests (but not others?).
