### ISSUE TITLE
Control Panel webapp details page shows logs for another app

### ISSUE THREAD

**Issue by andyhd** [ministryofjustice/analytics-platform#114]
## What happened?

* Went to [`occupeye_shiny_app` webapp detail page](https://controlpanel.services.alpha.mojanalytics.xyz/webapps/43/)
* Scrolled down to "App logs"
* Saw logs for `alpha-app-hr-exec-stats` webapp

## Expected behaviour

It should show the logs for `occupeye_shiny_app`

**Comment by andyhd** [comment]
The link to Kibana seems to work as expected, though

**Comment by calumabarnett** [comment]
Fixed in https://github.com/ministryofjustice/analytics-platform-control-panel/pull/782
