### ISSUE TITLE
Unable to access analytical tools from control panel #critical bug

### ISSUE THREAD

**Issue by dhepnerYJB** [ministryofjustice/analytics-platform#116]
**Be aware that these bug reports are publicly viewable, so please do not include any sensitive information in your bug report - this includes passwords, access tokens, sensitive data, etc**

Please use this text as a template, filling in the relevant bits and deleting the existing text,

Please search the existing issues to check that your issue hasn't already been reported.
If it has, please comment on the existing issue.

Choose a label for the issue from the "Labels" menu next to this input, to indicate the severity of the problem:
* critical bug: work is blocked, application crash, or loss of data
* major bug: common feature incorrectly/not functioning
* minor bug: other issues

## What happened?

Trying to access the analytical tools tab in the control panel for the first time, to add apps, and see the following message.

"Sorry, there is a problem with the service
Try again later.

Contact the Analytical Platform team if you need to make urgent changes to your webapps or data sources."

## Steps to reproduce the problem

1. Log-in
2. Click on the analytical platform tab
Can you reproduce the problem consistently?

## Expected behaviour

I expected to be able to view apps to add so I can use the thing.

**Comment by davidread** [comment]
Thanks for raising this issue - apologies for not writing here where we're at with it, although I believe my colleagues have been in touch via email.

A week ago @sh31 diagnosed the problem (user init helm chart failure) and did a fix. Let us know if you have any more trouble.
