### ISSUE TITLE
Static web hosting: external CDN in script src= blocked 

### ISSUE THREAD

**Issue by isichei** [ministryofjustice/analytics-platform#12]
Hosting a static webpage fails when calling:
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7/leaflet.css"/>
<script src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js"></script>
<script src="http://dimplejs.org/dist/dimple.v2.3.0.min.js"></script>

Trying to access javascript and css from leaflet and dimple seem to fail.

**Console log below:**
cdn.leafletjs.com/leaflet-0.7/leaflet.css Failed to load resource: net::ERR_INSECURE_RESPONSE
leaflet.js Failed to load resource: net::ERR_INSECURE_RESPONSE
dimple.v2.3.0.min.js Failed to load resource: net::ERR_INSECURE_RESPONSE
(index):369 Uncaught ReferenceError: L is not defined 
at (index):369

**Comment by RobinL** [comment]
What happens if you use a `src` that points to `https` rather than `http`

**Comment by isichei** [comment]
Still blocked

**Comment by RobinL** [comment]
Karik's confirmed you get the same error if the `src` points at a `https` resource

**Comment by isichei** [comment]
Exact same error response to htttps

**Comment by RobinL** [comment]
Also worth noting that some external resources load fine - specifically images from the tileserver.  See here:
https://github.com/moj-analytical-services/court_travel_time_tool/blob/942405f679147540efb3c1156f3cbcfe607dc078/www/index.html#L373

**Comment by kerin** [comment]
@isichei do you have a URL where we can see this issue?

**Comment by isichei** [comment]
Sorry for not getting back sooner! 

```
http://cdn.leafletjs.com/leaflet-0.7/leaflet.js
http://dimplejs.org/dist/dimple.v2.3.0.min.js
```

**Comment by xoen** [comment]
Closing.
