### ISSUE TITLE
"You are being redirected to the authorized application"

### ISSUE THREAD

**Issue by elliebyrne** [ministryofjustice/analytics-platform#120]
Problem accessing: rstudio.tools.alpha.mojanalytics.xyz

After I put in the Githib password and secondary authentication, I get  "alpha-analytics-moj
Oops!, something went wrong".

I have tried chrome and safari...any suggestions would be helpful! Thanks.

**Comment by itkdw** [comment]
You are being redirected to the authorized application.
If your browser does not redirect you back, please [click here](https://vscode.dev/redirect?code=5c635e76a46b61ae12e0&state=vscode%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253D4073104a-07eb-4e24-a4f7-0b3d2a638149%2526windowId%253D1) to continue.
