### ISSUE TITLE
When will RStudio be updated?

### ISSUE THREAD

**Issue by spilsr** [ministryofjustice/analytics-platform#132]
The current version of RStudio does not support the following packages: foreign and read_spss. I need to use these packages to run my code.

I noticed an issue was raised on this in November 2020. Could you please give me an update on when we will be able to access the latest version of RStudio?

Many thanks,
Becky

**Comment by davidread** [comment]
@spilsr Thanks for letting us know the concern. Have you tried [specifying an older version](https://user-guidance.services.alpha.mojanalytics.xyz/tools/package-management.html#installing-a-specific-version-of-a-package) of these packages, which may offer compatibility? I see that 'foreign' has been around for 20 years, so I expect going back a couple of versions will work.

Providing an updated R/Rstudio has gradually worked its way higher in priority as the R version has gotten older. I'm pleased to say that it's been actively worked on now for a few months. It's one of the top two priorities in the roadmap this quarter, but we don't make specific promises, I'm afraid. I hope that answers the question on the current status, but feel free to get in touch again here or on Slack in future.

**Comment by spilsr** [comment]
Hi David,

Thanks very much for your quick response. I didn’t realise ‘foreign’ was such an old package!

Best wishes,
Becky
