### ISSUE TITLE
Jenkins "grant_access_to_app" function doesn't accept uppercase letters

### ISSUE THREAD

**Issue by HaydenSansum** [ministryofjustice/analytics-platform#14]
I attempted to grant users access to two dashboard which contain upper case characters in their names (as appearing on the main MoJ Analytical Services Jenkins page). 

Using upper case letters caused the build to fail both time I attempted.

When using all lower case the build went through first time.

**Comment by andyhd** [comment]
The app name is normalized because it is used in URLs, which have various restrictions on allowed characters. However, the grant access job could accept an app name in title case (or any mix of cases) and normalize it automatically.

**Comment by andyhd** [comment]
I modified the grant_access script to accept mixed case app names
