### ISSUE TITLE
R Studio does not prompt new 2FA login every 24 hours

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#16]
## What happened?

I logged in several days in a row, without ever being prompted for 2FA code.

**Comment by andyhd** [comment]
@xoen @RobinL is this fixed now?

**Comment by xoen** [comment]
It should. Only thing is that now we went from session cookie not expiring at all to expiring every 1h, but RStudio deals horribly with that, so @kerin suggested to increase to 8h (same as SSO session lifetime).

**Comment by xoen** [comment]
Users are now challenged with 2FA every day (after 8h from login). Closing this.

PS: I'm going to deal with the RStudio error as a separate thing.
