### ISSUE TITLE
App deployment - scan of Github slow and API limit reached

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#17]
When creating a new app, it takes a long time to show up in Jenkins because we hit Github's rate limit

**Comment by andyhd** [comment]
Polling the Github API every few minutes is a really inefficient way of picking up new apps. We should see if we can get Github to notify Jenkins somehow, perhaps through a webhook.

**Comment by andyhd** [comment]
Deployment will be via Concourse from now on. Jenkins has been retired. Concourse deployments are triggered via a Github webhook on creation of a release, which is much more efficient.
