### ISSUE TITLE
Control panel issues

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#20]
## What happened?

![bug](https://user-images.githubusercontent.com/2608005/35576818-d84c8e80-05d7-11e8-895e-7b751541aeea.gif)

See above - the error message reads:

```
Internal Error
(/home/cpanel/app/templates/apps/new.html) [Line 11, Column 22] TypeError: Cannot read property 'length' of undefined
```
Note I'm a superuser.

---
_separate issues moved to other tickets_

**Comment by andyhd** [comment]
Ok, I've reproduced this error and figured out the cause. It's simply down to the app already existing. The API returns a 400 error to the frontend, but the frontend code doesn't handle it properly and so displays this rather less helpful error message.

**Comment by axemonkey** [comment]
Looking at the second GIF, I see a problem different to the one described. I see you clicking on the link to app data source bucket 'alpha-app-sentencing-policy-model' but then seeing the detail page for app data source bucket 'alpha-app-crime-in-prisons'.

**Comment by andyhd** [comment]
Fix ready for testing: https://github.com/ministryofjustice/analytics-platform-control-panel-frontend/pull/123

**Comment by andyhd** [comment]
@RobinL @axemonkey I will move the second issue into a new

**Comment by axemonkey** [comment]
Ah, and I've found the problem with the listed buckets linking to the wrong bucket detail pages.

Fix upcoming.

**Comment by andyhd** [comment]
@axemonkey I've moved that issue to https://github.com/ministryofjustice/analytics-platform/issues/22

**Comment by andyhd** [comment]
Fix is deployed to alpha
