### ISSUE TITLE
Control Panel reports no apps

### ISSUE THREAD

**Issue by andyhd** [ministryofjustice/analytics-platform#21]
## What happened?

@RobinL reported:
> The control panel reports that I have no webapps.  ('Your apps' reports 'none').
> 
> Aldo has checked the API backend database, which reports that I do have apps.

**Comment by andyhd** [comment]
I can't see any apps listed when I visit your user page either.

**Comment by andyhd** [comment]
Not sure what has changed since Aldo checked the API backend database, but when I do, I find no apps associated with your user @RobinL 

I can see a list of my own apps and I can see @axemonkey 's apps too.

**Comment by RobinL** [comment]
I can confirm i can see webapps now, closing
