### ISSUE TITLE
Frontend sometimes 'unaware' of user

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#24]
## What happened

Whilst logged in as a superuser, the 'superuser', 'data' and 'apps' tabs disappeared and I could only see the 'tools' tab.

Also the 'logged in as' text and 'sign out' in the header disappeared.  

Essentially it seemed that the platform could no longer 'see' what user was logged in

## Steps to reproduce the problem

Unfortunately the problem is intermittent, and we haven't figure out reliable way of reproducing it.

However, this has happened on multiple occasions:  typically by using the control panel's functions for a bit e.g. creating an app or an app bucket - you may run into this problem

**Comment by RobinL** [comment]
![image](https://user-images.githubusercontent.com/2608005/36302675-323aac34-1301-11e8-9564-9bbd3b68452f.png)

Here's an example

**Comment by axemonkey** [comment]
Handing off to @andyhd – session collision? Massive security hole? REDIS?

Good luck, and godspeed.
