### ISSUE TITLE
IAM role not being assigned to new apps

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#25]
When [this](https://github.com/moj-analytical-services/feedback_app
) new app is deployed, it is not assigned an IAM role and therefore is unable to access secure data.

Andy and Kerin have checked the in Kubernetes cluster, and the problem is that the deployment doesn't have an IAM role attached.

Note the deployment script hasn't changed.  It generates an IAM role name by hitting the control panel api.  It's just that that's returning an empty string.  

Here’s the groovy code which is returning an empty string for `AWS.IAMRole`: https://github.com/ministryofjustice/analytics-platform-jenkins-lib/blob/7644ab0c938008ed88502df8b3fd3d8fbd6c0672/vars/cpapi.groovy#L3

**Comment by RobinL** [comment]
![image](https://user-images.githubusercontent.com/2608005/36419238-42a10548-1629-11e8-977a-4234df390201.png)

**Comment by RobinL** [comment]
![image](https://user-images.githubusercontent.com/2608005/36419274-5acd4974-1629-11e8-9383-6155173370b7.png)

**Comment by jmoz** [comment]
The corresponding api call looks ok:

https://cpanelapi-master.services.alpha.mojanalytics.xyz/apps/?repo_url=https://github.com/moj-analytical-services/feedback-app

**Comment by jmoz** [comment]
Looks like the repo url changed from feedback-app to feedback_app which broke the api lookup.

**Comment by xoen** [comment]
After further investigation we concluded that the problem was not in the code but in the data input (app in CP-API had wrong `repo_url`)

Update this field made the deploy work as expected. Closing this.
