### ISSUE TITLE
'Revoke access' removes from inline policy but 'delete datasource' does not

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#26]
When you 'revoke access' to a data source, the inline `s3-access` policy is correctly modified.

However, when you 'delete datasource' this policy is not modified (i.e. the user retains access to the data source)

I expected to see the contents of the "alpha-everyone" bucket displayed
![image](https://user-images.githubusercontent.com/2608005/37400350-94ee0148-277c-11e8-97ed-fa65c97ea29c.png)

**Comment by andyhd** [comment]
Could you fill in the template, please?

The screenshot says "alpha-testbucket-rl2", but you expect to "alpha-everyone"?

**Comment by xoen** [comment]
I'm having a look.

Ticket: https://trello.com/c/f0gPNADq/720-4-when-user-deletes-bucket-directly-polwhen-delete-bucket-on-cp-clean-up-policies

**Comment by xoen** [comment]
This should now be fixed in both `dev` and `alpha`.
