### ISSUE TITLE
'Internal error - state mismatch' on the control panel

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#29]
## What happened?

A user was in the process of signing up.

When they went to the control panel, they received an error message 'internal error - state mismatch' and were therefore unable to access the control panel, and set themselves up.

I (Robin) have also frequently receive the same error message when accessing the control panel - and this usually happens the first time I access it during the day - but is not restricted solely to this.

## Steps to reproduce the problem

Access the control panel using the usual link.  The problem is frequent enough that if you access it a few times, the problem should occur.

**Comment by xoen** [comment]
FYI: This is in progress: https://trello.com/c/5czelJkJ/797-fix-internal-error-state-mismatch-error

**Comment by xoen** [comment]
@RobinL this is now in `alpha` so I'm closing this, let us know if this happen again.
