### ISSUE TITLE
Improve speed of packrat installs

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#3]
When cloning a project with a large number of dependencies, the platform can freeze up for quite some time whilst everything is compiled.

**Comment by RobinL** [comment]
I've been looking at various resources to try and understand how to improve this:

https://github.com/rstudio/packrat/issues/212

https://github.com/RobinL/cheatsheets_etc/blob/master/packrat_efficiency.md

https://github.com/rstudio/packrat/blob/master/R/cache.R

https://groups.google.com/forum/#!forum/packrat-discuss

The best solution I've come up with for R SHiny Docker is something like this:


```
# Set up another folder, create a packrat project 
# and install a bunch of default packages
WORKDIR /usr/my_project

# libraries includes one or more r files containing library(dplyr) type statements
ADD libraries .

RUN R -e "install.packages('packrat');  packrat::init(options=list(use.cache = TRUE));"
WORKDIR /srv/shiny-server

ADD packrat packrat

# Install some common R packages to prevent them having to be changed every time packrat.lock changes

RUN R -e  "packrat::set_opts(use.cache=TRUE); packrat::restore();"


```

**Comment by xoen** [comment]
Linux CRAN: https://cran.r-project.org/bin/linux/debian/

`There are i386 and amd64 binaries for jessie and wheezy`

[rocker/shiny](https://hub.docker.com/r/rocker/shiny) is based on [r-base](https://hub.docker.com/r/rocker/r-base/) which is based on debian:testing.

Debian testing codename should be `buster`:
https://wiki.debian.org/DebianReleases#Current_Releases.2FRepositories

**Comment by RobinL** [comment]
There's a chap called [Dirk](https://cran.r-project.org/bin/linux/debian/) who's been maintaining precompiled Debian packages since 2001.  

I found a [Stackoverflow he replied to back in 2012](https://stackoverflow.com/questions/11871394/create-r-binary-packages-for-linux-that-can-be-installed-on-different-machines) and asked a further question, which he responded to:

> Yes, you can. There used to be a service for that (google "cran2deb"), and we are trying to rebuild one. It won't be ready "soon" though. But you can very much proxy it locally. – Dirk Eddelbuettel 4 mins ago

This confirms that we can set up a local CRAN.  This is almost certainly the best/recommended approach (Dirk seems to be *the* expert here) - so looks like we need to investigate how `cran2deb` works.

**Comment by r4vi** [comment]
A potential fix for this is: https://github.com/ministryofjustice/analytics-platform-cran-proxy

**Comment by davidread** [comment]
We went from packrat to cran, so this is no longer an issue
