### ISSUE TITLE
Shiny app page vanishes (closes the webpage/tab)

### ISSUE THREAD

**Issue by HaydenSansum** [ministryofjustice/analytics-platform#30]
## What happened?

Shiny apps will close seemingly at random. This is separate from a standard time out (where the screen goes grey) in the sense that the tab/webpage where the app is being run will physically close. Rstudio still has the connection to the app open and navigating to the correct port will resume the app.

It has occurred on a few different MoJ Analytical Platform apps and upon testing also happens with the default old faithful app.

Rstudio will not display any error messages but the chrome console displays:
`rstudio-0.js:8941 POST https://haydensansum-rstudio.tools.alpha.mojanalytics.xyz/events/get_events net::ERR_EMPTY_RESPONSE`

## Steps to reproduce the problem

Difficult issue to reproduce as the time it takes before closing is not consistent, if it does close at all. When trying to replicate I have tried a number of different approaches with varying success.

* It will close either with or without any user input.
* The time it takes varies, generally within the first 5 minutes or not at all.
* It seems to close more frequently/faster when opened in a window/viewer than when opened externally.
* Will close in both chrome and firefox when opened in a browser window

**Comment by RobinL** [comment]
Thanks Hayden.  To flesh this one out with further details:

- This happens both on DOM1 machines on Firefox and on Chrome on Macbooks so we don't think it's machine specific
- When the window shuts down, one of the standard `get_events` ajax requests errors (goes red) in Chrome
- I don't think anything happens to the websocket connection (but we should double check) - it doesn't show any error 


Our next step is going to be to test the standard `rocker` R Studio to see if we can reproduce the problems running the vanilla image locally on a Macbook.

**Comment by RobinL** [comment]
Note that we believe this issue is caused by the websockets issue at #40

**Comment by davidread** [comment]
Hopefully this is fixed, along with: https://github.com/ministryofjustice/analytics-platform/issues/46#issuecomment-425108795
If we see it happening again, let's reopen.
