### ISSUE TITLE
Problems with some email addresses in the control panel

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#37]
Users are experiencing problems with some email addresses and some apps in Auth 0

<img width="745" alt="screen shot 2018-07-05 at 13 30 17" src="https://user-images.githubusercontent.com/2608005/42323335-c4057266-8057-11e8-890c-2459670aadfb.png">

**Comment by RobinL** [comment]
This looks like it's a problem with Auth0 getting confused.

In the situation where the app customer (who should have an email connection in Auth0) has an AP account, they get added to the app with a Github Connection.

Here's a reproducable example:

Remove lewis.crouch@justice.gov.uk from feedback app in control panel (apps/36).    Re-add him.  Log into Auth0 -> extensions -> authorization extension -> groups -> feedback app.  He shows up with a github connection

**Comment by RobinL** [comment]
This is a bit weird though because we definitely have AP users who are part of feedback app as 'email' connections.  Examples of this are me, jon roberts, mikael

**Comment by andyhd** [comment]
I took a quick look at this yesterday, and I can see that Katy successfully logged into crime-in-prisons many times in the past. The Auth0 logs show a CORS error with the last login to crime-in-prisons, but I don't know for certain if that was when Katy was trying to login. I'll investigate.

**Comment by andyhd** [comment]
I can reproduce the bug when adding a customer to an app with the same email as an existing platform user. The Control Panel checks whether a customer already exists with the specified email - but the bug is that it doesn't differentiate between _customers_ and _platform users_. I have a fix for this waiting to be merged now.

**Comment by sarahwebb81** [comment]
I still cannot log on to the Server, I am getting an error message "We're sorry something went wrong". When will this be resolved?

**Comment by andyhd** [comment]
This fix has now been deployed. @sarahwebb81 I checked your access specifically, and you should be able to login now.
