### ISSUE TITLE
Problems with shell in R Studio/Jupyter lab freezing

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#40]
When working in the shell in R Studio and Jupyter lab, the shell often freezes.

You need to refresh the page or start a new shell to fix this issue.

**Comment by RobinL** [comment]
This is an issue with web sockets.  We're currently using on ELB - AWS's Classic Elastic Load Balancer, which doesn't support websockets

We need to move to something that support websockets e.g. AWS's  Network Load Balancer.

Note this is the same underlying issue that is causing #30

**Comment by RobinL** [comment]
This one is quite a big one so likely to take some time for us to fix

**Comment by davidread** [comment]
We think this is now fixed with the newer nginx ingress, as per comments: https://github.com/ministryofjustice/analytics-platform/issues/46#issuecomment-425108795
