### ISSUE TITLE
Auth0 'something went wrong' on app login

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#45]
Login to http://testdeploys3.apps.alpha.mojanalytics.xyz/login is failing.

I've doubled checked that email address exists in Auth0 and that Auth0 is detecting the attempted login

Auth0 logs showing 
```
{
  "date": "2018-08-16T08:11:01.495Z",
  "type": "fco",
  "description": "Origin http://testdeploys3.apps.alpha.mojanalytics.xyz is not allowed. Behavior used for check: WEB ORIGINS",
```
Error message displayed is:
![image](https://user-images.githubusercontent.com/2608005/44197327-37b95980-a136-11e8-9f45-1f92510c6ba6.png)

**Comment by RobinL** [comment]
A few further details from the auth0 log:
![image](https://user-images.githubusercontent.com/2608005/44197569-e5c50380-a136-11e8-8f6b-f5b5f1f42457.png)

**Comment by RobinL** [comment]
This seems to be affected new deployments, but logging into existing apps is fine

**Comment by RobinL** [comment]
Have tried again - this time with the app called rshiny-test-deployment.  Same error

**Comment by andyhd** [comment]
I have confirmed that this bug occurs when you use `http://` instead of `https://`. We should be automatically redirecting to HTTPS, but that seems to have been turned off - perhaps another NLB/nginx-ingress related issue.

**Comment by davidread** [comment]
https redirect is fixed now
