### ISSUE TITLE
Jupyter lack of responsiveness

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#48]
Issues are similar to what is being experienced in R Studio [here](https://github.com/ministryofjustice/analytics-platform/issues/46)

Robin:  I navigated to my Jupyter Lab url at https://robinl-jupyter-lab.tools.alpha.mojanalytics.xyz/lab?. 
The browser  said it was 'Connecting...' at the bottom left for 20 seconds plus, after which it successfully let me into Jupyter Lab

Robin:  I navigated to my Jupyter Lab url at https://robinl-jupyter-lab.tools.alpha.mojanalytics.xyz/lab?. 
The browser immediately gave me a 503.

Note: these problems are intermittent, sometimes Jupyter Lab loads immediately and successfully

**Comment by RobinL** [comment]
![image](https://user-images.githubusercontent.com/2608005/44842336-78889680-ac3d-11e8-91ca-6e901d9da536.png)

**Comment by davidread** [comment]
@RobinL said: 
> We made some changes to the platform yesterday which we _think_ have resolved the recent networking problems. ... Jupyter users should now have a much smoother experience, without frequent freezing and error messages.
