### ISSUE TITLE
login loop when AP is open in another window

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#52]
## What happened?

* HB: I can't get onto the platform on my mac on 102PF wifi. I enter my 2 step verification and then it sends me back to the login page.
* ST: this happens to me regularly: make sure you're not logged in to the platform in any other browser window you've already got open?

## Steps to reproduce the problem
(Tested: alpha, outside corporate network)
1. In browser tab 1 log into AP control panel
2. In browser tab 2 open AP control panel
3. In browser tab 2 log out
4. In browser tab 2 log in. Observe it asks you to login again (i.e. a second time in a row - a loop)

## Expected behaviour
After log in it should show you the control panel.

**Comment by davidread** [comment]
We think this is to do with MFA. Could be the same issue as: https://github.com/ministryofjustice/analytics-platform/issues/42

**Comment by xoen** [comment]
Can't reproduce. Is this still a problem @davidread ?

I tried steps in Safari while connected to 102PF and it didn't happen to me.

Hang on a second. I actually managed to reproduce but only in Chrome: It may be a Chrome-specific issue.
