### ISSUE TITLE
Remove GOV.UK branding

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#54]
We shouldn't have GOV.UK branding: 
<img width="100" alt="screen shot 2018-08-30 at 11 28 37" src="https://user-images.githubusercontent.com/307612/44846358-09646f80-ac48-11e8-89a1-631a6290a053.png">
in our header and favicon. Also we need to switch font from nta (also it requires a paid licence).

https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk#if-your-service-isnt-on-govuk

We could use MOJ logo or create an AP one.

**Comment by axemonkey** [comment]
I recently removed all NTA/govuk fonts from MPS, and have a handy override stylesheet you might like.

https://github.com/ministryofjustice/moving-people-safely/blob/master/app/assets/stylesheets/moving_people_safely/_font_override.scss
