### ISSUE TITLE
"Proxy server is refusing connections" error occasionally on DOM1

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#56]
Affects only DOM1 machines (because their web browsers are configured to route traffic through a proxy).

## Questions

* [x] Is this only a problem on the DOM1 network?
    * It affects DOM1 machines (they have a proxy setup in the browser)
* [x] Does this only affect starting R Studio, or does it affect other actions in AP?
    * No. Screenshot shows cpanel and KB says it affects Jupyter too.
* [ ] Is there a simple workaround - just to do the action again and it'll probably work?
* [x] Screenshot of the error
* [ ] Is this only a problem for NLB (not ELB Classic)?

## Raw discussion

KB: Neither RStudio or Jupyter are working for me now & the control panel is struggling to load properly. RStudio is still listed as idled but I have the options "open" or "restart".

Me: KB what happens when you press 'open'?

KB: It doesn't load at all, it says "The proxy server is refusing connections"

TH: the proxy server issue is a recurring IT issue, not directly platform related
at least IT are aware of it now

TH: well this is frustrating, it seems the proxy server issues are now isolated to the platform (i.e. I can access other websites just fine).

ST: yeah that's been the case for me all day

Note: ST, KB & TH are all running today on DOM1

**Comment by katharinebreeze** [comment]
See below for a screenshot. I currently have the same problem for the control panel, jupyter and RStudio (after restarting my laptop). Refreshing the page doesn't work. Switching from the purple cable to wifi seemed to work for me once but hasn't worked this time (tried a couple of times).
![image](https://user-images.githubusercontent.com/36629221/44867028-acd07700-ac7e-11e8-8e20-d530a3eb8f38.png)

**Comment by davidread** [comment]
@katharinebreeze shared with me that her machine is DOM1 and the browser has a configured web proxy.

**Comment by davidread** [comment]
Talking with the analysts, we've characterized the seriousness of this issue:
* it affected 2 analysts, for 3 days last week, significant affects on their work those days and then it cleared up
* since then the problem has not come back

Theories of the cause:
* the DOM1 proxy is taking some strain and can't or won't accept new requests/connections
* RStudio and Jupyter are likely to use and hold onto connections than the average website, with their REPL, terminal and dashboard functionality, and use of web sockets.
* because it's not affecting other browsing, maybe the proxy is choosing to limit the number of connections for AP (across all users), whilst other domains are not constrained.

We agreed that since it's gone away for now, we won't do anything, but if it comes back we'll work on it more, which sounds like talking to the DOM1 people.

**Comment by davidread** [comment]
Not heard of this for a while - closing.
