### ISSUE TITLE
User unable to access their R Studio/network timeouts

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#60]
User `ianaelliott` is unable to access his R Studio, even after restarting the pod.

His pod is running, but attempts to access it at http://ianaelliott-rstudio.tools.alpha.mojanalytics.xyz/ timeout

![image](https://user-images.githubusercontent.com/2608005/45414644-c8bb1c00-b673-11e8-8310-426b745fd8f9.png)

This does not seem related to the network he's using (Quantum), because his R Studio is also inaccessible from MoJ Digital Wifi on a macbook

**Comment by RobinL** [comment]
This issue appears to be affecting a lot more users - at least another 4 have reported the issue

**Comment by davidread** [comment]
This has been resolved. There was a problem unidling/restarting R Studio.

We were unable to schedule pods, due to a k8s master node being unhealthy. We fixed it by deleting the node (EC2 instance). The issue went away, and the auto-scaling group recreated the master node without intervention.

**Comment by xoen** [comment]
We think this may have been caused by one of the kubernetes master stopping working.
We terminated that faulty instance and replaces with a new one and things should be back to operational now.

**Comment by davidread** [comment]
We have fixed the broken master node again and R Studios are working fine. However it points to something underlying issue causing this to happen twice in 24hrs, so I've opened a separate ticket for that: https://github.com/ministryofjustice/analytics-platform/issues/64
