### ISSUE TITLE
Apps don't work in Quantum

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#62]
Deployed Shiny apps grey out after 3-4 seconds when access from Quantum.

We're note sure of when this issue started but it was probably either:

- When we switched from ELB to NLB
- At a similar time to the move to Canary Wharf, at which point it's likely there were changes to the Quantum network

**Comment by davidread** [comment]
I think that this is due to the new Quantum IP address, which may well be associated with the 10SC move.

The work to resolve this is here:
https://trello.com/c/J95tIaai/1307-update-quantum-ip-ranges-following-10sc-move

**Comment by davidread** [comment]
Actually it looks like Phil logged in on Monday via a Quantum IP address that should already be whitelisted. I've asked him for more info.

**Comment by davidread** [comment]
As @RobinL has suggested with the NLB label, we think this is due to the general network issues within AP as collected together here: https://github.com/ministryofjustice/analytics-platform/issues/46

**Comment by davidread** [comment]
Hopefully we can move deployed apps to the newer nginx soon, like we did for R Studio and Jupyter, to resolve this issue.

**Comment by davidread** [comment]
@RobinL says this is fixed 🎆 

Since last night's k8s upgrade and redeploy of nginx on alpha, we're now using the newer nginx on apps, resulting in reliable connection.

Previously on Quantum machines it was broken due to:
> websockets issues
> the browser is old and didn’t handle disconnects very nicely so they greyed out
