### ISSUE TITLE
Cant access S3 buckets through Juypterlab on the platform

### ISSUE THREAD

**Issue by jamiefraser77** [ministryofjustice/analytics-platform#67]
I am trying to access S3 buckets through Juypterlab on the platform, but I get credential related errors. I can access buckets just fine through R and the AWS website. The problem seems to be that boto3 cant grab my AWS credentials.

![screen shot 2018-09-14 at 16 06 43](https://user-images.githubusercontent.com/41285706/45621117-2b972380-ba77-11e8-9109-7a21d01b7279.png)
![screen shot 2018-09-14 at 16 07 53](https://user-images.githubusercontent.com/41285706/45621118-2b972380-ba77-11e8-9434-2910ac98eb49.png)

**Comment by RobinL** [comment]
This is likely caused by lack of the correct annotation on Jamie's Jupyter deployment, but it remains for us to find out why the annotation doesn't exist

**Comment by davidread** [comment]
My fault, I set the wrong name on creation. I'll fix it.

**Comment by davidread** [comment]
I've fixed the annotation now - should work.
