### ISSUE TITLE
Need to update R Studio docker configuration to point to a better CRAN mirror

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#68]
```
Ben Fortescue [12:15 PM]:

Doing a `getOption("repos")` on a restarted session (no project open) gives me
                                            ```CRAN 
"https://mran.microsoft.com/snapshot/2017-11-30"
```

I can verify I get the same, which means that users trying to install the latest versions of packages get the most recent version as at November 2017.

We should update this to a non-snapshotted version

**Comment by Thomas-Hirsch** [comment]
A temporary solution is to run `option(repos = "https://cran.rstudio.com/")` in R, substituting `"https://cran.rstudio.com/"` with your desired repository. This will change the repository for a given project, but will need to be run by the user for every new project.
