### ISSUE TITLE
RStudio hanging - CREST

### ISSUE THREAD

**Issue by RossKen** [ministryofjustice/analytics-platform#7]
## What happened?

Running some simple functions from the CREST.toolbox takes an unusually long time. On many occasions RStudio hangs for nearly an hour and then disconnects/crashes - more recently there has been no option to cancel the function running within Rstudio so have to refresh the browser window to get back to normal.

## Steps to reproduce the problem

Try to access flatfile_meta.csv (a 35 KB file) via s3browser. Go to alpha-dag-crest-data-engineering, click into metadata folder, select flatfile_meta.csv.

## Expected behaviour

Expect to be able to download/access datasets from s3, but RStudio crashes before this happens

## Actual behaviour

Ran for an hour then RStudio crashed. 
Karik tried the same thing and was instantaneous on his platform account.

**Comment by andyhd** [comment]
@RossKen is this still a problem?

**Comment by RobinL** [comment]
Hopefully this will be fixed when we give users the ability to restart their R Studio

**Comment by RobinL** [comment]
Closing as this problem doesn't seem to be recurrent
