### ISSUE TITLE
Shiny apps greying out after 5 mins +

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#71]
The change to NLB has made a big improvements to Shiny app 'greying out' problems.

However, we're still seeing these issues.  They no longer happen immediately (within the first 30 seconds of running the app), but they can happen over longer time horizons (after roughly 5 mins +).

I've observed this behaviour using R Shiny within R Studio, and we've also had reports from deployed app customers

**Comment by davidread** [comment]
Here's a screenshot, for reference:
![image 4](https://user-images.githubusercontent.com/307612/52292488-bf0cba80-296c-11e9-937b-77c6c7586218.png)

**Comment by davidread** [comment]
It's suggested that networks like Quantum are not conducive to keeping websockets etc open. This well be a smart firewall closing things after a time. 🤷‍♂️ 

We're experimenting with adding a line to the Shiny app's Dockerfile that tells it not to use various transport protocols. We need to cut it down to what works, but as a starting point it's: ```RUN echo "disable_protocols websocket xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile xdr-polling xhr-polling iframe-xhr-polling;" >> /etc/shiny-server/shiny-server.conf```
