### ISSUE TITLE
Auth0 says "Enter your email..." trying to access apps

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#73]
## What happened?

MF reported that when accessing [coroner-stat-tool-ext app](https://coroner-stat-tool-ext.apps.alpha.mojanalytics.xyz)  you see Auth0 dialog: "Enter your email to sign in or create an account":
![capture](https://user-images.githubusercontent.com/307612/46610816-58c97580-cafb-11e8-9926-7d0c844f5da5.PNG)

> All the users have been granted access. They are external users using the emailed magic link.

I'm also now seeing this with: http://probation-consultation-tool.apps.alpha.mojanalytics.xyz/

**Comment by davidread** [comment]
@r4vi mentioned solving it for MF's app:
> there was something wrong with the auth0 config for this app

**Comment by r4vi** [comment]
@davidread this field was blank in auto0 
![image](https://user-images.githubusercontent.com/565628/46610889-f5901100-cb03-11e8-89b4-392243e67004.png)

we've had issues with this in the past where setting it via API doesn't "stick". I think @andyhd updated the API client to ensure this was set (I remember @xoen reviewing a PR about it a long time ago)

my first though was that this app predated that change.

**Comment by andyhd** [comment]
I think this is to do with users having been added to the wrong group in Auth0 - there have been "duplicate" groups created when app name normalization has been applied differently (usually capitalization). I thought I cleared all that up, but it's possible that this predates the fixes, or that something is still normalizing group names incorrectly somewhere.

👋

**Comment by davidread** [comment]
This app had a problem with the Auth0 field "Allowed Web Origins" being blank. I've fixed that manually.

I determined problem by checking the Auth0 logs for the time of log-in. The message said:
> The specified redirect_uri 'https://probation-consultation-tool.apps.alpha.mojanalytics.xyz/callback' does not have a registered origin.

**Comment by davidread** [comment]
We think this was due to service issues with auth0 yesterday. Closing, for now.
