### ISSUE TITLE
AP not accessible from DOM1 for some users some of the time

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#74]
Since yesterday, several users on DOM1 have had issues connecting to AP URLs (including control panel, R Studio, Jupyter, apps). It doesn't happen to all users. It comes and goes.

Error messages:
* IE: ‘the proxy server isn’t responding’
* Firefox: ‘problem loading page - the connection has timed out’
* Chrome: ‘the site can’t be reached’

We think this is a problem with Dom1/ATOS - some sort of blocking of our domain or maybe some sort of shaping policy.

@RobinL raised an urgent ticket with ATOS yesterday and we're waiting for a response.

**Comment by r4vi** [comment]
ATOS Incident number is: 899735

**Comment by davidread** [comment]
10th October - ATOS resolved "a wide range of connectivity problems users are facing, following changes to proxy rules"

12th October - a few DOM1 users suffered problems again - I believe these were resolved the same day.

So I think this particular issue with DOM1 is fixed. However there we've known for a while it is [a bit flakey](https://github.com/ministryofjustice/analytics-platform/issues/75).
