### ISSUE TITLE
Concourse shows "TLS handshake timeout" error

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#92]
e.g. 
```
2019/02/19 17:12:13 put failed: failed to set status: Post https://api.github.com/repos/moj-analytical-services/airflow-dags/statuses/f94747cf507b971ea2d9af24357addfd93488f00: net/http: TLS handshake timeout
```
[<img width="1054" alt="screen shot 2019-02-19 at 17 45 01" src="https://user-images.githubusercontent.com/307612/53035778-1d0dc780-346e-11e9-9732-f7d9815bee57.png">](https://concourse.services.alpha.mojanalytics.xyz/teams/main/pipelines/airflow/jobs/lint/builds/74)

Another example: https://api.github.com/repos/moj-analytical-services/airflow-dags/statuses/237d91d552bb285c3697e2fafdc07ba2bdb90b1e

First noted 16/1/19

This appears intermittently. We believe concourse is simply being flaky.

## Workaround

Simply run the concourse build again (manually).

**Comment by outsidecoder** [comment]
Did you find a solution to your issue?  What version of concourse were/are you running?  Are you using github.com/telia-oss/github-pr-resource ?

**Comment by davidread** [comment]
@outsidecoder I'm not aware of a solution, I'm afraid. This would be concourse v3.14.1 - I'm not sure if it still occurs. BTW we're not using github-pr-resource. Sorry not to be more help

**Comment by juan-yields** [comment]
Hello @outsidecoder. I am having just the same issue and using `github.com/telia-oss/github-pr-resource`.  

Currently running Concourse `7.7.0`. And this happens randomly on different repos and different pipelines. 

I would appreciate if you could please share any workaround/fix.

Cheers!
