### ISSUE TITLE
Airflow bomb error

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#93]
## What happened?

When opening airflow:
![airflow_bomb1](https://user-images.githubusercontent.com/307612/53475609-46c77f80-3a68-11e9-8fd1-998f2eca9a42.PNG)
![airflow_bomb2](https://user-images.githubusercontent.com/307612/53475608-46c77f80-3a68-11e9-8395-d2e2d1ca161e.PNG)

Reported by @samtazzyman. Not affecting other users.

## Workaround

Delete cookies and it works again.

**Comment by samtazzyman** [comment]
This isn't true, sadly - it affected @r4vi too, and it turned out not to be the cookie error.

(Cookie error was something I experience before once)

**Comment by davidread** [comment]
This turned out to be caused by changes to the pod which meant redis wasn't configured, which is now fixed.
