### ISSUE TITLE
"0 ingresses" error viewing app in cpanel

### ISSUE THREAD

**Issue by HaydenSansum** [ministryofjustice/analytics-platform#97]
When accessing some apps through the control panel (which have been created by an admin through the panel) it returns an internal error about 0 ingresses. The suspicion is that this is due to the app having not yet been deployed through concourse.

For example the CriminalFinesPredictor app was created but has not yet had a deployment through concourse and visiting the relevant page on github returns:

```
Internal Error
Found 0 ingresses for app CriminalFinesPredictor
```

It would be useful if you could access the backend set up of apps (adding customers etc.) without having to actually deploy them first.

**Comment by davidread** [comment]
This is a problem with the cpanel. @andyhd perhaps you can take a look?
https://cpanel-master.services.alpha.mojanalytics.xyz/apps/92
<img width="729" alt="Screen Shot 2019-03-25 at 17 33 51" src="https://user-images.githubusercontent.com/307612/54941262-52517d80-4f24-11e9-8739-3f022c93ecc4.png">

**Comment by davidread** [comment]
The same issue is seen with coroner-stat-tool https://cpanel-master.services.alpha.mojanalytics.xyz/apps/34
