### ISSUE TITLE
"Access denied" error logging into apps

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#98]
This has happened with 2 quantum users.

User sees this during app login:
<img width="264" alt="Screen Shot 2019-03-26 at 15 47 59" src="https://user-images.githubusercontent.com/307612/55011943-93a66380-4fde-11e9-93be-dae6afd263a3.png">

In auth0 logs it says: `Cannot read property 'toLowerCase' of null`
<img width="834" alt="Screen Shot 2019-03-26 at 15 47 03" src="https://user-images.githubusercontent.com/307612/55012025-ad47ab00-4fde-11e9-8c82-ab90cb6e01bc.png">
<img width="460" alt="Screen Shot 2019-03-26 at 15 45 26" src="https://user-images.githubusercontent.com/307612/55012029-afaa0500-4fde-11e9-92c0-e11469e02d7b.png">

**Comment by r4vi** [comment]
happens when the passwordless user has been created in `auth0` without a `username` field. You can't set this afterwards. You can fix it be deleting the user and when try attempt to login again they will be recreated with a `username`

**Comment by calumabarnett** [comment]
Another user has experienced this issue with the CCMA-Gold-Scorecard-App. @r4vi can this be fixed by deleting and re-adding the user in control panel alone or does the user need to be deleted in Auth0 as well?

**Comment by r4vi** [comment]
@calumabarnett which user? (send me a message) I'll need to check in auth0 and see if they don't have username set. If they don't then the only remedy is to delete and re-add

**Comment by r4vi** [comment]
I think this line needs to explicitly set `nickname` https://github.com/ministryofjustice/analytics-platform-control-panel/blob/ee6159cf8855c3a6da319bcabced18d73fc168e5/controlpanel/api/auth0.py#L157

**Comment by andyhd** [comment]
I can only find one email user associated with the `toLowerCase` error message. They have a `nickname` set, so I assume the user was recreated? @r4vi do you have any idea why they didn't have one originally? I can't see what makes them different from any of the other email users that work. Where is the code that calls `toLowerCase`?

**Comment by r4vi** [comment]
yeah they've all probably been recreated... @andyhd this is the rule: https://manage.auth0.com/dashboard/eu/alpha-analytics-moj/rules/rul_xMy5gTXg43c5wYla

**Comment by r4vi** [comment]
which comes from: https://github.com/ministryofjustice/analytics-platform-auth0/blob/alpha/rules/Lowercase-the-user-nickname.js

**Comment by r4vi** [comment]
@andyhd no idea why they didn't have one but it seems to be random

**Comment by andyhd** [comment]
I think the fix is best applied in the rule - we don't use nicknames for passwordless users

**Comment by r4vi** [comment]
That's a quick fix... but what if we did start relying on it? Or an app did (we now expose the user profile to webapps). We should do the other fix too

**Comment by davidread** [comment]
Fixed in https://github.com/ministryofjustice/analytics-platform-control-panel/pull/720 we think
